version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - .:/var/www  # Mount the project root directory
      - ./nginx.localhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www  # Mount the project root directory
